import AirIcon from '@mui/icons-material/Air';
import Battery6BarIcon from '@mui/icons-material/Battery6Bar';
import GpsFixedIcon from '@mui/icons-material/GpsFixed';
import MemoryIcon from '@mui/icons-material/Memory';
import PrecisionManufacturingIcon from '@mui/icons-material/PrecisionManufacturing';
import ViewInArIcon from '@mui/icons-material/ViewInAr';

export const CUBESAT_VIEWBOX = {
    width: 100,
    height: 145,
};

export const TELEMETRY_FIELD_CONFIG = {
    missionTime: {
        id: 'missionTime',
        label: 'Mission time',
        sourceLabel: 'm-time',
        keys: ['m-time'],
        kind: 'text',
        formatter: (value) => value || '--',
    },
    flightId: {
        id: 'flightId',
        label: 'Flight ID',
        sourceLabel: 'Flight ID',
        keys: ['Flight ID'],
        kind: 'text',
        formatter: (value) => value || '--',
    },
    ubloxUtc: {
        id: 'ubloxUtc',
        label: 'Ublox UTC',
        sourceLabel: 'Ublox UTC',
        keys: ['Ublox UTC'],
        kind: 'text',
        formatter: (value) => value || '--',
    },
    latitude: {
        id: 'latitude',
        label: 'Latitude',
        sourceLabel: 'U Lat',
        keys: ['U_Lat', 'U Lat'],
        chartKey: 'U_Lat',
        kind: 'number',
        decimals: 5,
        unit: 'deg',
    },
    longitude: {
        id: 'longitude',
        label: 'Longitude',
        sourceLabel: 'U Long',
        keys: ['U_Long', 'U Long'],
        chartKey: 'U_Long',
        kind: 'number',
        decimals: 5,
        unit: 'deg',
    },
    altitude: {
        id: 'altitude',
        label: 'Altitude',
        sourceLabel: 'U Alt',
        keys: ['U_Alt', 'U Alt'],
        chartKey: 'U_Alt',
        kind: 'number',
        decimals: 1,
        unit: 'm',
    },
    speed: {
        id: 'speed',
        label: 'Speed',
        sourceLabel: 'Speed',
        keys: ['Speed'],
        chartKey: 'Speed',
        kind: 'number',
        decimals: 2,
        unit: 'm/s',
    },
    verticalSpeed: {
        id: 'verticalSpeed',
        label: 'Vertical speed',
        sourceLabel: 'Vert speed',
        keys: ['Vert_speed', 'Vert speed'],
        chartKey: 'Vert_speed',
        kind: 'number',
        decimals: 2,
        unit: 'm/s',
    },
    satellites: {
        id: 'satellites',
        label: 'Satellites',
        sourceLabel: '#Sat',
        keys: ['#_Sat', '#Sat'],
        chartKey: '#_Sat',
        kind: 'number',
        decimals: 0,
        unit: 'sat',
    },
    pressure: {
        id: 'pressure',
        label: 'Pressure',
        sourceLabel: 'Pressure',
        keys: ['Pressure'],
        chartKey: 'Pressure',
        kind: 'number',
        decimals: 2,
        unit: 'hPa',
    },
};

export const CUBESAT_SUBSYSTEMS = [
    {
        id: 'power',
        name: 'Power / Battery',
        shortName: 'Power',
        description: 'Upper energy storage and power conditioning stack feeding the avionics chain.',
        details: 'No direct power telemetry is exposed in the current CSV, but the battery block is mapped and ready for future voltage, current, temperature, or charge fields.',
        color: '#d2b04c',
        statusMode: 'noTelemetry',
        telemetryFieldIds: [],
        summaryFieldIds: [],
        chartFieldIds: [],
        icon: Battery6BarIcon,
        hotspot: {
            anchor: { x: 61.2, y: 29.3 },
            labelOffset: { x: 8, y: -9 },
            polygon: [
                [54.9, 28.2],
                [75.9, 37.6],
                [67.9, 57.4],
                [46.5, 48.3],
            ],
        },
        emptyMessage: 'No telemetry available for the power subsystem yet.',
    },
    {
        id: 'navigation',
        name: 'GPS / GNSS / Navigation',
        shortName: 'Navigation',
        description: 'Position, altitude, speed, and satellite lock are mapped to the navigation electronics in the central avionics stack.',
        details: 'This block aggregates the Ublox time reference plus the platform kinematics used for tracking and mission reconstruction.',
        color: '#4cbc74',
        statusMode: 'navigation',
        telemetryFieldIds: ['ubloxUtc', 'latitude', 'longitude', 'altitude', 'speed', 'verticalSpeed', 'satellites'],
        summaryFieldIds: ['altitude', 'speed', 'satellites'],
        chartFieldIds: ['altitude', 'speed'],
        icon: GpsFixedIcon,
        hotspot: {
            anchor: { x: 52.8, y: 45.7 },
            labelOffset: { x: 8, y: -8 },
            polygon: [
                [45, 52.7],
                [67.7, 62.8],
                [59.5, 79.8],
                [36.8, 69.1],
            ],
        },
        emptyMessage: 'Navigation telemetry is mapped, but no live values are currently available.',
    },
    {
        id: 'obc',
        name: 'OBC / Avionics / Mission Control',
        shortName: 'OBC',
        description: 'Core embedded control boards responsible for mission timing, flight identity, and onboard coordination.',
        details: 'This area is placed on the green mid-stack boards, matching the avionics cluster visible in the provided CubeSat render.',
        color: '#2e9f69',
        statusMode: 'operational',
        telemetryFieldIds: ['missionTime', 'flightId'],
        summaryFieldIds: ['missionTime', 'flightId'],
        chartFieldIds: [],
        icon: MemoryIcon,
        hotspot: {
            anchor: { x: 42.1, y: 61.4 },
            labelOffset: { x: 8, y: 3 },
            polygon: [
                [29.7, 79.2],
                [56.8, 91.4],
                [51.1, 99],
                [25.9, 88.9],
            ],
        },
        emptyMessage: 'Mission-control telemetry fields are mapped, but the current sample has no valid value.',
    },
    {
        id: 'environment',
        name: 'Environmental / Barometer',
        shortName: 'Barometer',
        description: 'Environmental sensing block used here as the pressure and atmospheric context subsystem.',
        details: 'Pressure is the only environmental field currently present, so this subsystem is intentionally narrow and easy to extend later.',
        color: '#4fb7d6',
        statusMode: 'sensor',
        telemetryFieldIds: ['pressure'],
        summaryFieldIds: ['pressure'],
        chartFieldIds: ['pressure'],
        icon: AirIcon,
        hotspot: {
            anchor: { x: 38.5, y: 68.6 },
            labelOffset: { x: 8, y: 3 },
            polygon: [
                [25.9, 89.3],
                [50.7, 100.8],
                [47.9, 108.2],
                [23.1, 95.8],
            ],
        },
        emptyMessage: 'No pressure telemetry is available yet for the environmental module.',
    },
    {
        id: 'structure',
        name: 'Structure / Chassis',
        shortName: 'Structure',
        description: 'Primary frame, rails, and support braces holding the CubeSat stack together.',
        details: 'This subsystem is descriptive for now and highlights the external support structure rather than a live telemetry source.',
        color: '#8797ab',
        statusMode: 'descriptive',
        telemetryFieldIds: [],
        summaryFieldIds: [],
        chartFieldIds: [],
        icon: ViewInArIcon,
        hotspot: {
            anchor: { x: 69.8, y: 52.9 },
            labelOffset: { x: -34, y: -8 },
            polygon: [
                [80.3, 32.6],
                [92.3, 25.7],
                [51.5, 135.3],
                [41.4, 136.1],
            ],
        },
        emptyMessage: 'No structural telemetry is available in the current dataset. This card remains descriptive by design.',
    },
    {
        id: 'payload',
        name: 'Payload / Lower Module',
        shortName: 'Payload',
        description: 'Configurable lower cylindrical bay reserved for payload or future sensing modules.',
        details: 'The orange lower section is treated as a configurable payload zone so that mission-specific telemetry can be added later without changing the UI structure.',
        color: '#ee8a22',
        statusMode: 'configurable',
        telemetryFieldIds: [],
        summaryFieldIds: [],
        chartFieldIds: [],
        icon: PrecisionManufacturingIcon,
        hotspot: {
            anchor: { x: 32, y: 85 },
            labelOffset: { x: 8, y: -7 },
            polygon: [
                [26.9, 107.1],
                [46.3, 116],
                [36.4, 136.1],
                [18.5, 128.6],
            ],
        },
        emptyMessage: 'No payload telemetry is currently mapped. This module is intentionally left configurable for future sensors.',
    },
];

export const DEFAULT_CUBESAT_SUBSYSTEM_ID = 'navigation';
