version: 1
disable_existing_loggers: false

formatters:
  colored:
    "()": colorlog.ColoredFormatter
    format: '[%(asctime)s] %(name)s %(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s'
    log_colors:
      DEBUG: cyan
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: red,bg_white

handlers:
  default:
    class: logging.StreamHandler
    formatter: colored
    stream: ext://sys.stdout

loggers:
  uvicorn.error:
    level: WARNING
    handlers: [default]
    propagate: no
  uvicorn.access:
    level: WARNING
    handlers: [default]
    propagate: no
  asyncio:
    level: WARNING
    handlers: [default]
    propagate: no

root:
  level: DEBUG
  handlers: [default]
  propagate: no
